name: removal_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.0.2
  flutter_riverpod: ^2.5.1
  dio: ^5.4.1
  flutter_svg: ^2.0.10+1
  video_editor: ^3.0.0
  image_picker: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  video_player: ^2.9.1
  flutter_downloader: ^1.11.8
  path_provider: ^2.1.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/icon/core/removal_app_icon.png"
    min_sdk_android: 21

flutter_native_splash:
    color: "#141414"
    image: assets/images/icon/core/removal_splash_icon.png

    ios: true
    android: true

    android_12:
      image: assets/images/icon/core/removal_splash_icon.png
      icon_background_color: "#141414"

flutter:

  uses-material-design: true

  assets:
    - assets/images/icon/on_boarding/
    - assets/images/icon/main/
    - assets/images/icon/core/
    - assets/images/icon/my_page/
    - assets/images/icon/video/
    - assets/images/logo/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900

